
//requetes 1 
CREATE VIEW
Requete1view (ID_GARE_DEPART, SAISON, MOIS, Montant_total)
AS
SELECT ID_GARE_DEPART, SAISON, MOIS, SUM(PRIX) AS "Montant total"
FROM TICKET JOIN 
DATE_DATE ON TICKET.ID_DATE = DATE_DATE.ID_DATE
GROUP BY ID_GARE_DEPART, SAISON, MOIS
ORDER BY ID_GARE_DEPART;




//requetes 2
CREATE VIEW
Requete2view (ID_GARE_DEPART, ID_GARE_ARRIVEE, MOIS, Montant_total)
AS
SELECT ID_GARE_DEPART, ID_GARE_ARRIVEE, MOIS, SUM(prix)  AS "Montant total"
FROM TICKET 
JOIN GARE ON TICKET.ID_GARE_DEPART = GARE.ID_GARE 
JOIN GARE ON TICKET.ID_GARE_ARRIVEE = GARE.ID_GARE 
JOIN DATE_DATE ON TICKET.ID_DATE = DATE_DATE.ID_DATE
GROUP BY ID_GARE_DEPART, ID_GARE_ARRIVEE, MOIS
ORDER BY ID_GARE_DEPART, ID_GARE_ARRIVEE;


//requetes 3
CREATE VIEW
Requete3view (ID_GARE_DEPART, ID_GARE_ARRIVEE, TYPE_TRAIN, PRIX_MOYEN)
AS
SELECT ID_GARE_DEPART, ID_GARE_ARRIVEE, COALESCE(TYPE_TRAIN, 'Pour tous les types de trains'), AVG(PRIX) AS "Prix moyen"
FROM TICKET JOIN TRAIN ON TICKET.ID_TRAIN=TRAIN.ID_TRAIN
GROUP BY ROLLUP(TYPE_TRAIN), ID_GARE_DEPART, ID_GARE_ARRIVEE;


//requetes 4
CREATE VIEW
Requete4view (ID_PROMOTION, CODE_DEPARTEMENT_GARE, ANNEE,NB_TICKETS)
SELECT PROMOTION.ID_PROMOTION, CODE_DEPARTEMENT_GARE, ANNEE, COUNT(*) AS "Nb tickets"
FROM TICKET JOIN
PROMOTION ON TICKET.ID_PROMOTION = PROMOTION.ID_PROMOTION
JOIN GARE ON TICKET.ID_GARE_DEPART = GARE.ID_GARE
JOIN DATE_DATE ON TICKET.ID_DATE = DATE_DATE.ID_DATE
GROUP BY PROMOTION.ID_PROMOTION, CODE_DEPARTEMENT_GARE, ANNEE
ORDER BY PROMOTION.ID_PROMOTION, CODE_DEPARTEMENT_GARE;




//requetes 5
CREATE VIEW
Requete5view (ID_PROMOTION, CARTE_REDUCTION,NB_TICKETS)
AS
SELECT PROMOTION.ID_PROMOTION, CARTE_REDUCTION, COUNT(*) AS "Nombre de tickets"
FROM TICKET
JOIN VOYAGEUR ON TICKET.ID_VOYAGEUR = VOYAGEUR.ID_VOYAGEUR
JOIN PROMOTION ON TICKET.ID_PROMOTION=PROMOTION.ID_PROMOTION
WHERE PROMOTION.ID_PROMOTION != 1
GROUP BY PROMOTION.ID_PROMOTION, CARTE_REDUCTION;




//requetes 6
CREATE VIEW
Requete6view (GARE_DEPART, GARE_ARRIVEE,TYPE_TRAIN)
AS
SELECT ID_GARE_DEPART, ID_GARE_ARRIVEE, COALESCE(TYPE_TRAIN, 'Pour tous les types de trains') AS TYPE_TRAIN, AVG(TAUX_OCCUPATION) AS "Taux d'occupation moyen"
FROM TRAJET 
JOIN TRAIN ON TRAJET.ID_TRAIN = TRAIN.ID_TRAIN
JOIN GARE G ON TRAJET.ID_GARE_DEPART = G.ID_GARE
JOIN GARE GG ON TRAJET.ID_GARE_ARRIVEE = GG.ID_GARE
GROUP BY ROLLUP(TYPE_TRAIN), ID_GARE_DEPART, ID_GARE_ARRIVEE;





//requetes 7
CREATE VIEW
Requete7view (CODE_DEPARTEMENT_GARE,CODE_VILLE_GARE,TAUX_OCCUPATION_MOYEN)
AS
SELECT CODE_DEPARTEMENT_GARE, CODE_VILLE_GARE, AVG(TAUX_OCCUPATION) AS "Taux d'occupation moyen"
FROM TRAJET JOIN GARE ON ID_GARE_DEPART = GARE.ID_GARE 
GROUP BY CODE_DEPARTEMENT_GARE, CODE_VILLE_GARE
ORDER BY CODE_DEPARTEMENT_GARE, CODE_VILLE_GARE;



//requetes 8
CREATE VIEW
Requete8view (ID_GARE_DEPART,ID_GARE_ARRIVEE,MOIS,JOUR,TAUX_MAX)
AS
SELECT ID_GARE_DEPART, ID_GARE_ARRIVEE, MOIS, JOUR, MAX(TAUX_OCCUPATION) AS "Taux max"
FROM TRAJET JOIN DATE_DATE on TRAJET.ID_DATE=DATE_DATE.ID_DATE
GROUP BY ID_GARE_DEPART, ID_GARE_ARRIVEE, MOIS, JOUR
ORDER BY ID_GARE_DEPART, ID_GARE_ARRIVEE, MOIS, JOUR;


//requetes 9
CREATE VIEW
Requete9view (CODE_DEPARTEMENT_GARE,CODE_VILLE_GARE,ID_GARE_ARRIVEE,TAUX_OCCUPATION_MOYEN)
AS
SELECT CODE_DEPARTEMENT_GARE, CODE_VILLE_GARE, T.ID_GARE_ARRIVEE, AVG(TAUX_OCCUPATION) AS "Taux moyen d'occupation"
FROM TRAJET T JOIN GARE ON T.ID_GARE_ARRIVEE = GARE.ID_GARE
GROUP BY CODE_DEPARTEMENT_GARE, CODE_VILLE_GARE, T.ID_GARE_ARRIVEE
ORDER BY CODE_DEPARTEMENT_GARE, CODE_VILLE_GARE, T.ID_GARE_ARRIVEE;



//requetes 10
CREATE VIEW
Requete10view (ID_GARE_ARRIVEE,TAUX_OCCUPATION_ARRIVEE,TAUX_OCCUPATION_DEPART)
AS
SELECT ID_GARE_ARRIVEE, CMPT1 AS "Taux d'occ a l'arrivee", CMPT2 AS "Taux d'occ au depart"
FROM
(	SELECT ID_GARE_ARRIVEE, AVG(TAUX_OCCUPATION) AS CMPT1
	FROM TRAJET t
	GROUP BY ID_GARE_ARRIVEE
) ARR
JOIN
(	SELECT ID_GARE_DEPART, AVG(TAUX_OCCUPATION) AS CMPT2
	FROM TRAJET t
	GROUP BY ID_GARE_DEPART
) DEP ON ARR.ID_GARE_ARRIVEE = DEP.ID_GARE_DEPART
WHERE ARR.CMPT1 >= DEP.CMPT2
ORDER BY ID_GARE_ARRIVEE;
