
package proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Ihotel", targetNamespace = "http://hotel/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ihotel {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toString", targetNamespace = "http://hotel/", className = "proxy.ToString")
    @ResponseWrapper(localName = "toStringResponse", targetNamespace = "http://hotel/", className = "proxy.ToStringResponse")
    @Action(input = "http://hotel/Ihotel/toStringRequest", output = "http://hotel/Ihotel/toStringResponse")
    public String toString();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setAddr", targetNamespace = "http://hotel/", className = "proxy.SetAddr")
    @ResponseWrapper(localName = "setAddrResponse", targetNamespace = "http://hotel/", className = "proxy.SetAddrResponse")
    @Action(input = "http://hotel/Ihotel/setAddrRequest", output = "http://hotel/Ihotel/setAddrResponse")
    public void setAddr(
        @WebParam(name = "arg0", targetNamespace = "")
        Adresse arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNom", targetNamespace = "http://hotel/", className = "proxy.GetNom")
    @ResponseWrapper(localName = "getNomResponse", targetNamespace = "http://hotel/", className = "proxy.GetNomResponse")
    @Action(input = "http://hotel/Ihotel/getNomRequest", output = "http://hotel/Ihotel/getNomResponse")
    public String getNom();

    /**
     * 
     * @return
     *     returns proxy.Adresse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddr", targetNamespace = "http://hotel/", className = "proxy.GetAddr")
    @ResponseWrapper(localName = "getAddrResponse", targetNamespace = "http://hotel/", className = "proxy.GetAddrResponse")
    @Action(input = "http://hotel/Ihotel/getAddrRequest", output = "http://hotel/Ihotel/getAddrResponse")
    public Adresse getAddr();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setNom", targetNamespace = "http://hotel/", className = "proxy.SetNom")
    @ResponseWrapper(localName = "setNomResponse", targetNamespace = "http://hotel/", className = "proxy.SetNomResponse")
    @Action(input = "http://hotel/Ihotel/setNomRequest", output = "http://hotel/Ihotel/setNomResponse")
    public void setNom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getid", targetNamespace = "http://hotel/", className = "proxy.Getid")
    @ResponseWrapper(localName = "getidResponse", targetNamespace = "http://hotel/", className = "proxy.GetidResponse")
    @Action(input = "http://hotel/Ihotel/getidRequest", output = "http://hotel/Ihotel/getidResponse")
    public int getid();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrix", targetNamespace = "http://hotel/", className = "proxy.GetPrix")
    @ResponseWrapper(localName = "getPrixResponse", targetNamespace = "http://hotel/", className = "proxy.GetPrixResponse")
    @Action(input = "http://hotel/Ihotel/getPrixRequest", output = "http://hotel/Ihotel/getPrixResponse")
    public float getPrix(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "getNombre_etoile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNombre_etoile", targetNamespace = "http://hotel/", className = "proxy.GetNombreEtoile")
    @ResponseWrapper(localName = "getNombre_etoileResponse", targetNamespace = "http://hotel/", className = "proxy.GetNombreEtoileResponse")
    @Action(input = "http://hotel/Ihotel/getNombre_etoileRequest", output = "http://hotel/Ihotel/getNombre_etoileResponse")
    public int getNombreEtoile();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "getNombre_lit")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNombre_lit", targetNamespace = "http://hotel/", className = "proxy.GetNombreLit")
    @ResponseWrapper(localName = "getNombre_litResponse", targetNamespace = "http://hotel/", className = "proxy.GetNombreLitResponse")
    @Action(input = "http://hotel/Ihotel/getNombre_litRequest", output = "http://hotel/Ihotel/getNombre_litResponse")
    public int getNombreLit();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Reserver")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Reserver", targetNamespace = "http://hotel/", className = "proxy.Reserver")
    @ResponseWrapper(localName = "ReserverResponse", targetNamespace = "http://hotel/", className = "proxy.ReserverResponse")
    @Action(input = "http://hotel/Ihotel/ReserverRequest", output = "http://hotel/Ihotel/ReserverResponse")
    public boolean reserver(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Chambre>
     */
    @WebMethod(operationName = "getList_chambre")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList_chambre", targetNamespace = "http://hotel/", className = "proxy.GetListChambre")
    @ResponseWrapper(localName = "getList_chambreResponse", targetNamespace = "http://hotel/", className = "proxy.GetListChambreResponse")
    @Action(input = "http://hotel/Ihotel/getList_chambreRequest", output = "http://hotel/Ihotel/getList_chambreResponse")
    public List<Chambre> getListChambre();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<proxy.Chambre>
     */
    @WebMethod(operationName = "can_res_chambre")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "can_res_chambre", targetNamespace = "http://hotel/", className = "proxy.CanResChambre")
    @ResponseWrapper(localName = "can_res_chambreResponse", targetNamespace = "http://hotel/", className = "proxy.CanResChambreResponse")
    @Action(input = "http://hotel/Ihotel/can_res_chambreRequest", output = "http://hotel/Ihotel/can_res_chambreResponse")
    public List<Chambre> canResChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "setNombre_lit")
    @RequestWrapper(localName = "setNombre_lit", targetNamespace = "http://hotel/", className = "proxy.SetNombreLit")
    @ResponseWrapper(localName = "setNombre_litResponse", targetNamespace = "http://hotel/", className = "proxy.SetNombreLitResponse")
    @Action(input = "http://hotel/Ihotel/setNombre_litRequest", output = "http://hotel/Ihotel/setNombre_litResponse")
    public void setNombreLit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setPrix", targetNamespace = "http://hotel/", className = "proxy.SetPrix")
    @ResponseWrapper(localName = "setPrixResponse", targetNamespace = "http://hotel/", className = "proxy.SetPrixResponse")
    @Action(input = "http://hotel/Ihotel/setPrixRequest", output = "http://hotel/Ihotel/setPrixResponse")
    public void setPrix(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "setList_chambre")
    @RequestWrapper(localName = "setList_chambre", targetNamespace = "http://hotel/", className = "proxy.SetListChambre")
    @ResponseWrapper(localName = "setList_chambreResponse", targetNamespace = "http://hotel/", className = "proxy.SetListChambreResponse")
    @Action(input = "http://hotel/Ihotel/setList_chambreRequest", output = "http://hotel/Ihotel/setList_chambreResponse")
    public void setListChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Chambre> arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "setNombre_etoile")
    @RequestWrapper(localName = "setNombre_etoile", targetNamespace = "http://hotel/", className = "proxy.SetNombreEtoile")
    @ResponseWrapper(localName = "setNombre_etoileResponse", targetNamespace = "http://hotel/", className = "proxy.SetNombreEtoileResponse")
    @Action(input = "http://hotel/Ihotel/setNombre_etoileRequest", output = "http://hotel/Ihotel/setNombre_etoileResponse")
    public void setNombreEtoile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
